import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

const eur = (n: any) => "€" + Number(n ?? 0).toFixed(2);

// Build and download a clean A4 invoice PDF from the e-invoice.be document JSON.
export function downloadInvoicePDF(doc: any) {
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const M = 40;
  const R = 360;

  pdf.setFontSize(22);
  pdf.text("INVOICE", M, 52);

  // Vendor (sender)
  pdf.setFontSize(10);
  pdf.setTextColor(60);
  pdf.text(String(doc.vendor_name || ""), M, 82);
  if (doc.vendor_address) pdf.text(String(doc.vendor_address), M, 96);
  if (doc.vendor_tax_id) pdf.text("VAT / ID: " + doc.vendor_tax_id, M, 110);

  // Invoice meta (right)
  pdf.text("Invoice no:  " + (doc.invoice_id || doc.id || ""), R, 82);
  pdf.text("Date:  " + (doc.invoice_date || ""), R, 96);
  pdf.text("Due:  " + (doc.due_date || ""), R, 110);

  // Bill-to
  pdf.setTextColor(20);
  pdf.text("Bill to", M, 144);
  pdf.setTextColor(60);
  pdf.text(String(doc.customer_name || ""), M, 158);
  if (doc.customer_address) pdf.text(String(doc.customer_address), M, 172);
  if (doc.customer_tax_id) pdf.text("VAT / ID: " + doc.customer_tax_id, M, 186);

  // Line items
  const body = (doc.items || []).map((it: any) => [
    String(it.description ?? ""),
    String(Number(it.quantity ?? 0)),
    String(it.unit ?? ""),
    eur(it.unit_price),
    (it.tax_rate ?? "0") + "%",
    eur(it.amount)
  ]);
  autoTable(pdf, {
    startY: 206,
    head: [["Description", "Qty", "Unit", "Unit price", "VAT", "Amount"]],
    body,
    theme: "striped",
    headStyles: { fillColor: [37, 99, 235] },
    styles: { fontSize: 9, cellPadding: 5 },
    columnStyles: { 3: { halign: "right" }, 5: { halign: "right" } }
  });

  let y = (pdf as any).lastAutoTable.finalY + 24;
  const put = (label: string, val: string, bold = false) => {
    pdf.setFont("helvetica", bold ? "bold" : "normal");
    pdf.text(label, R, y);
    pdf.text(val, 555, y, { align: "right" });
    y += 16;
  };
  put("Subtotal", eur(doc.subtotal));
  put("VAT", eur(doc.total_tax));
  put("Total " + (doc.currency || "EUR"), eur(doc.invoice_total), true);

  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(120);
  pdf.setFontSize(9);
  let fy = y + 22;
  if (doc.payment_term) { pdf.text("Payment terms: " + doc.payment_term, M, fy); fy += 14; }
  pdf.text("PEPPOL e-invoice (UBL) via e-invoice.be · generated by Voice Invoice", M, fy);

  pdf.save(`invoice-${doc.invoice_id || doc.id || "document"}.pdf`);
}
